name: 'Bulk GitHub Repository Settings Sync'
description: 'Update repository settings in bulk for multiple GitHub repositories'

branding:
  icon: 'settings'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access (requires repo scope)'
    required: true
  github-api-url:
    description: 'GitHub API URL (e.g., https://api.github.com for GitHub.com or https://ghes.domain.com/api/v3 for GHES). Instance URL is auto-derived.'
    required: false
    default: '${{ github.api_url }}'
  repositories:
    description: 'Comma-separated list of repositories (owner/repo format) or "all" for all repos in the organization/user'
    required: false
  repositories-file:
    description: 'Path to YAML file containing repository list'
    required: false
  owner:
    description: 'Owner (user or organization) name - required when using "all" for repositories or when using custom property filtering (must be an organization for custom properties)'
    required: false
  custom-property-name:
    description: 'Name of the custom property to filter repositories by (organization custom property)'
    required: false
  custom-property-value:
    description: 'Comma-separated list of custom property values to match. Repositories with any of these values will be included.'
    required: false
  allow-squash-merge:
    description: 'Allow squash merging pull requests'
    required: false
  allow-merge-commit:
    description: 'Allow merge commits for pull requests'
    required: false
  allow-rebase-merge:
    description: 'Allow rebase merging pull requests'
    required: false
  allow-auto-merge:
    description: 'Allow auto-merge on pull requests'
    required: false
  delete-branch-on-merge:
    description: 'Automatically delete head branches after pull requests are merged'
    required: false
  allow-update-branch:
    description: 'Always suggest updating pull request branches'
    required: false
  immutable-releases:
    description: 'Enable immutable releases to prevent release deletion and modification'
    required: false
  code-scanning:
    description: 'Enable or disable default code scanning setup'
    required: false
  enable-default-code-scanning:
    description: 'DEPRECATED: Use code-scanning instead. Enable default code scanning setup.'
    required: false
    deprecationMessage: 'enable-default-code-scanning is deprecated. Use code-scanning instead.'
  secret-scanning:
    description: 'Enable or disable secret scanning for repositories'
    required: false
  secret-scanning-push-protection:
    description: 'Enable or disable secret scanning push protection for repositories'
    required: false
  dependabot-alerts:
    description: 'Enable or disable Dependabot alerts (vulnerability alerts) for repositories. Also enables the dependency graph.'
    required: false
  dependabot-security-updates:
    description: 'Enable or disable Dependabot security updates for repositories'
    required: false
  topics:
    description: 'Comma-separated list of topics to set on repositories (replaces existing topics)'
    required: false
  dependabot-yml:
    description: 'Path to a dependabot.yml file to sync to .github/dependabot.yml in target repositories'
    required: false
  dependabot-pr-title:
    description: 'Title for pull requests when updating dependabot.yml'
    required: false
    default: 'chore: update dependabot.yml'
  gitignore:
    description: 'Path to a .gitignore file to sync to .gitignore in target repositories (preserves repo-specific content after marker)'
    required: false
  gitignore-pr-title:
    description: 'Title for pull requests when updating .gitignore'
    required: false
    default: 'chore: update .gitignore'
  rulesets-file:
    description: 'Path to a JSON file containing repository ruleset configuration to sync to target repositories'
    required: false
  delete-unmanaged-rulesets:
    description: 'Delete all other rulesets besides the one being synced'
    required: false
    default: 'false'
  pull-request-template:
    description: 'Path to a pull request template file to sync to .github/pull_request_template.md in target repositories'
    required: false
  pull-request-template-pr-title:
    description: 'Title for pull requests when updating pull request template'
    required: false
    default: 'chore: update pull request template'
  workflow-files:
    description: 'Comma-separated list of workflow file paths to sync to .github/workflows/ in target repositories (e.g., "./workflows/ci.yml,./workflows/release.yml")'
    required: false
  workflow-files-pr-title:
    description: 'Title for pull requests when updating workflow files'
    required: false
    default: 'chore: sync workflow configuration'
  autolinks-file:
    description: 'Path to a JSON file containing autolink references to sync to target repositories'
    required: false
  copilot-instructions-md:
    description: 'Path to a copilot-instructions.md file to sync to .github/copilot-instructions.md in target repositories'
    required: false
  copilot-instructions-pr-title:
    description: 'Title for pull requests when updating copilot-instructions.md'
    required: false
    default: 'chore: update copilot-instructions.md'
  package-json-file:
    description: 'Path to a package.json file to use as source for syncing npm scripts and/or engines'
    required: false
  package-json-sync-scripts:
    description: 'Sync npm scripts from package-json-file to target repositories'
    required: false
    default: 'true'
  package-json-sync-engines:
    description: 'Sync engines field from package-json-file to target repositories (useful for Node.js version requirements)'
    required: false
    default: 'true'
  package-json-pr-title:
    description: 'Title for pull requests when updating package.json'
    required: false
    default: 'chore: update package.json'
  dry-run:
    description: 'Preview changes without applying them (logs what would be changed)'
    required: false
    default: 'false'

outputs:
  updated-repositories:
    description: 'Number of repositories successfully updated'
  failed-repositories:
    description: 'Number of repositories that failed to update'
  results:
    description: 'JSON array of update results for each repository'

runs:
  using: 'node20'
  main: 'dist/index.js'
